### ISSUE TITLE
"Dive is too deep and too long!!" error is ignored, dive will still be added

### ISSUE THREAD

**Issue by shuanang** [CS2113-AY1819S1-W13-2/main#114]
add ds/10082018 ts/0700 de/10082018 te/0800 ss/0745 d/16 pg/A l/Sentosa tz/+8
followed by
add ds/10082018 ts/0800 de/10082018 te/0815 ss/0807 d/16 pg/A l/Sentosa tz/+8

The second dive is a invalid dive. 12 minutes is the maximum, hence will throw "Dive is too deep and too long". However, dive will STILL be added, resulting in a wrong pressure group calculation (i.e from a start PG of "T" -> the app will show a random value like "C" for end pressure group)

**Comment by shuanang** [comment]
add ds/07112018 ts/0700 de/07112018 te/0800 ss/0745 d/16 pg/A l/Sentosa tz/+8
Then
add ds/07112018 ts/0600 de/07112018 te/0630 ss/0625 d/10 pg/A l/Sentosa tz/+8     <— invalid dive, max is 72 minutes. Here is 77mins
Gives Dive too deep and too long error, but dive is still added

**Comment by TTTaus** [comment]
Apparently now if that error appears, the dive sessions gets cleared...
