### ISSUE TITLE
"Safety Stop is either earlier than start of dive or later than the end of dive" error thrown wrongly

### ISSUE THREAD

**Issue by shuanang** [CS2113-AY1819S1-W13-2/main#124]
"add ds/07112018 ts/0700 de/03112018 te/0800 ss/0745 d/16 pg/A l/Sentosa tz/+8" 

date end before date start -> throws wrong error "Safety Stop is either earlier than start of dive or later than the end of dive. It should be in chronological order!" 

same thing happens if time end before time starts...

**Comment by cjunxiang** [comment]
ok bro thanks

**Comment by cjunxiang** [comment]
resolves with newest PR.
