### ISSUE TITLE
edit command throws wrong exceptions

### ISSUE THREAD

**Issue by shuanang** [CS2113-AY1819S1-W13-2/main#137]
add ds/11112018 ts/0700 de/11112018 te/0705 ss/0702 d/16 l/Sentosa tz/+8
edit 1 d/43
edit 1 te/2300
edit 1 d/43 should say "dive is too long and too deep, max you can go is 42m"
edit 1 te/2300 should say "dive is too long and too deep"
but now both of them are throwing "Invalid time format! (Not 24Hr format) "

**Comment by arjo129** [comment]
@shuanang Bug is in your code..
