### ISSUE TITLE
Color the labels

### ISSUE THREAD

**Issue by arjo129** [CS2113-AY1819S1-W13-2/main#36]
make it more colorful.

**Comment by arjo129** [comment]
One of the groups I was talking to changed the CSS class programatically and updated the CSS files instead.

**Comment by TTTaus** [comment]
Did they use 3rd party support? https://wiki.openjdk.java.net/display/OpenJFX/CSS+API+to+support+custom+UI+Controls

**Comment by TTTaus** [comment]
Pls ignor my previous comment

**Comment by arjo129** [comment]
closed by #68
