### ISSUE TITLE
Pressure group calculation does not take into account first/repeat dive of day

### ISSUE THREAD

**Issue by shuanang** [CS2113-AY1819S1-W13-2/main#72]
Difference between first dive calculation (Refer to Table 1 of PADI) 
and repeat dive of day EVEN if the user has surfaced till his/her pressure group is "A" .
Even if pressure group of user has reached "A" after first dive, they are required to add the residual nitrogen time to their next actual (dived) bottom time (Refer to Table 3 then 1 of PADI)
Programme now does not account for this.
E.g first dive at 10m for 10 minutes. According to Table 1 of PADI, pressure group is "A". User wants to go for another dive right after at 10m for 10 minutes. However, according to Table 3, user has to add 10 minutes to residual nitrogen time to his/her next actual bottom time - so his/her new pressure group should be "B" - 20 minutes (10 actual + 10 residual) at 10m, instead of "A" which the program now outputs.

**Comment by arjo129** [comment]
Fixed by PR #73
